# -------------------------------------------------------------------------------------------------------
# File Name: CONSTANTS.py
# Author:   Jai Verma
# Description: A file for storing variables / data that is repeatedly used throughout the project.
# -------------------------------------------------------------------------------------------------------


TEAMS = ['Royal Challengers Bangalore', 'Kings XI Punjab', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Punjab Kings', 'Lucknow Super Giants',
       'Gujarat Titans']