# -------------------------------------------------------------------------------------------------------
# File Name: data.py
# Author:   Jai Verma
# Description: A file for storing variables / data that is repeatedly used throughout the project.
# -------------------------------------------------------------------------------------------------------
from utils.read_data import matches

SEASONS = matches['season'].unique()

TEAMS = matches['team1'].unique()

STADIUMS = matches['venue'].unique()

IPL_FACTS_BY_SEASON = {
    2008: ["First Ever IPL: The inaugural season of the IPL was played in 2008 with eight teams, and Rajasthan Royals, led by Shane Warne, won the championship.",
        "First IPL Century: Brendon McCullum scored the first-ever IPL century, hitting 158* for Kolkata Knight Riders against Royal Challengers Bangalore.",
        "First Hat-trick: Amit Mishra of Delhi Daredevils took the first-ever hat-trick in IPL history."],

    2009: ["Winner: Deccan Chargers won their first IPL title, defeating Royal Challengers Bangalore in the final.",
        "Player of the Tournament: Adam Gilchrist was named Player of the Tournament for his explosive batting performance.",
        "First Overseas IPL Player to Win the Orange Cap: Matthew Hayden, from Chennai Super Kings, won the Orange Cap with 572 runs.",
        "First IPL Final in South Africa: Due to security issues in India, IPL 2009 was moved to South Africa."],

    2010: ["Winner: Chennai Super Kings won their first IPL title under MS Dhoni.",
           "First Ever IPL Final at DY Patil Stadium: The final was held at DY Patil Stadium, Navi Mumbai."],
    
    2011: ["Winner: Chennai Super Kings won their second consecutive title.",
           "Highest Score by a Team: Royal Challengers Bangalore set the record for the highest total in IPL history at that time with 215/1 against Delhi Daredevils.",
            "First Ever IPL Team to Reach 3 Consecutive Finals: Chennai Super Kings became the first team to make it to the final three years in a row."],

    2012: ["First Time KKR Won the Title: Kolkata Knight Riders, under Gautam Gambhir, won their first-ever IPL title.",
            "Most Sixes in a Season: Chris Gayle hit 59 sixes during IPL 2012.",
            "Winner: Kolkata Knight Riders won their first title, defeating Chennai Super Kings."],
   
    2013: ["Winner: Mumbai Indians won their first IPL title.",
           "First IPL Season to Feature a Major Scandal: The 2013 season was marred by the spot-fixing and betting scandal, leading to suspensions of some players.",
            "First Time Mumbai Indians Defeated Chennai Super Kings in the Final: Mumbai defeated Chennai in the final to win their first title."],
   
    2014: ["Winner: Kolkata Knight Riders won their second IPL title, defeating Kings XI Punjab in the final.",
           "Highest Total in a Match: Royal Challengers Bangalore scored the highest total of the season, 215/1, against Sunrisers Hyderabad.",
            "Most Sixes in a Match: The match between Royal Challengers Bangalore and Sunrisers Hyderabad saw 21 sixes, the most in a match during this season."],
    
    2015: ["Winner: Mumbai Indians won their second title, defeating Chennai Super Kings.",
           "Most Boundaries in a Season: Chris Gayle (Royal Challengers Bangalore) hit the most boundaries in the season, with 92.",
            "Highest Run Chase: Mumbai Indians chased down a massive total of 190/4 against Rajasthan Royals."],
    
    2016: ["Chennai Super Kings (CSK) were banned from the IPL for two years (2016-2017) due to their involvement in a match-fixing scandal.",
           "Winner: Sunrisers Hyderabad won their first IPL title.",
           "Most Sixes in a Season: Chris Gayle hit the most sixes in the 2016 season with 41 sixes.",
           ],
    
    2017: ["Winner: Mumbai Indians won their third IPL title.",
           "Most Matches Won by a Team: Mumbai Indians won 10 matches in the league phase of IPL 2017."
           "Orange Cap Winner: David Warner (Sunrisers Hyderabad) scored 641 runs."],
    
    2018: ["Winner: Chennai Super Kings won their third IPL title.",
           "Highest Partnership: The highest partnership in IPL 2018 was between Shane Watson and Ambati Rayudu (CSK), which contributed significantly in their title-winning campaign.",
           "First Time CSK Returned After Ban: Chennai Super Kings made a successful return after a two-year ban and won the IPL in their comeback season."],
    
    2019: ["Winner: Mumbai Indians won their fourth IPL title.",
           "Most Sixes: Kieron Pollard (Mumbai Indians) hit 31 sixes in the season.",
           "First IPL Final Decided by Super Over: The final between Mumbai Indians and Chennai Super Kings ended in a nail-biting Super Over, with Mumbai emerging victorious."],
    
    2020: ["Winner: Mumbai Indians won their fifth IPL title.",
           "Most Runs by a Captain: Rohit Sharma (Mumbai Indians) scored the most runs among IPL captains.",
           "First IPL Played in the UAE: The 2020 IPL season was moved to the UAE due to the pandemic, and it was the second time the IPL was played outside India."],
    
    2021: ["Winner: Chennai Super Kings won their fourth IPL title.",
           "First Time a Team Won After Losing the Previous Final: Chennai Super Kings became the first team to win the IPL after losing the previous season's final.",
           "Most Sixes: Chris Gayle (Punjab Kings) hit the most sixes in the season."],
    
    2022: ["Winner: Gujarat Titans won their first-ever IPL title in their debut season, defeating Rajasthan Royals in the final.",
           "Most Runs by a Team: Rajasthan Royals scored the highest total of the season (222/2) against Gujarat Titans.",
           "Debut Team: Gujarat Titans and Lucknow Super Giants were the two new teams that joined the IPL in 2022."],
    
    2023: ["Winner: Chennai Super Kings won their fifth IPL title, the most by any team, defeating Gujarat Titans in the final.",
           "Record Final: The IPL 2023 final between Chennai Super Kings and Gujarat Titans saw the highest-ever number of runs scored in a final, with 211 runs being scored.",
           "Player of the Tournament: Ruturaj Gaikwad (Chennai Super Kings) was awarded Player of the Tournament for his consistent performance in the season."],
    
    2024: ["Gujarat Titans' Lowest Total: Gujarat Titans set the record for the lowest total in IPL 2024, scoring just 89 runs against Delhi Capitals​",
           "Sunrisers Hyderabad's Record Total: In an exhilarating match, Sunrisers Hyderabad set the highest team total in IPL history by scoring 287 runs against Royal Challengers Bangalore (RCB)​",
            "Travis Head's Fastest Century: Travis Head became the fourth player in IPL history to score the fastest century, joining the ranks of Chris Gayle, Yusuf Pathan, and David Miller​",
            "Mayank Yadav's Pace: Mayank Yadav bowled the fastest delivery of IPL 2024, clocking in at 156.7 km/h, making him the fourth fastest in IPL history​",
            "Home Advantage in Openers: The home teams won all eight opening matches of the IPL 2024 season, a strong statement about the home ground advantage​"]
}


PLAYERS = ['A Ashish Reddy', 'A Badoni', 'A Chandila', 'A Chopra',
       'A Choudhary', 'A Dananjaya', 'A Flintoff', 'A Kamboj', 'A Kumble',
       'A Manohar', 'A Mishra', 'A Mithun', 'A Mukund', 'A Nehra',
       'A Nel', 'A Nortje', 'A Raghuvanshi', 'A Singh', 'A Symonds',
       'A Tomar', 'A Uniyal', 'A Zampa', 'AA Bilakhia', 'AA Chavan',
       'AA Jhunjhunwala', 'AA Kazi', 'AA Kulkarni', 'AA Noffke',
       'AB Agarkar', 'AB Barath', 'AB Dinda', 'AB McDonald',
       'AB de Villiers', 'AC Blizzard', 'AC Gilchrist', 'AC Thomas',
       'AC Voges', 'AD Hales', 'AD Mascarenhas', 'AD Mathews', 'AD Nath',
       'AD Russell', 'AF Milne', 'AG Murtaza', 'AG Paunikar', 'AJ Finch',
       'AJ Hosein', 'AJ Turner', 'AJ Tye', 'AK Markram', 'AL Menaria',
       'AM Nayar', 'AM Rahane', 'AM Salvi', 'AN Ahmed', 'AN Ghosh',
       'AP Dole', 'AP Majumdar', 'AP Tare', 'AR Bawne', 'AR Patel',
       'AS Joseph', 'AS Rajpoot', 'AS Raut', 'AS Roy', 'AS Yadav',
       'AT Carey', 'AT Rayudu', 'AU Rashid', 'AUK Pathan', 'AV Wankhade',
       'Abdul Basith', 'Abdul Samad', 'Abdur Razzak', 'Abhishek Sharma',
       'Abishek Porel', 'Akash Deep', 'Akash Madhwal', 'Akash Singh',
       'Aman Hakim Khan', 'Anand Rajan', 'Anirudh Singh', 'Ankit Sharma',
       'Ankit Soni', 'Anmolpreet Singh', 'Anuj Rawat', 'Anureet Singh',
       'Arjun Tendulkar', 'Arshad Khan', 'Arshad Khan (2)',
       'Arshdeep Singh', 'Ashutosh Sharma', 'Atharva Taide', 'Avesh Khan',
       'Azhar Mahmood', 'Azmatullah Omarzai', 'B Akhil', 'B Aparajith',
       'B Chipli', 'B Geeves', 'B Indrajith', 'B Kumar', 'B Laughlin',
       'B Lee', 'B Sai Sudharsan', 'B Stanlake', 'B Sumanth', 'BA Bhatt',
       'BA Stokes', 'BAW Mendis', 'BB McCullum', 'BB Samantray',
       'BB Sran', 'BCJ Cutting', 'BE Hendricks', 'BJ Haddin', 'BJ Hodge',
       'BJ Rohrer', 'BMAJ Mendis', 'BR Dunk', 'BR Sharath',
       'BW Hilfenhaus', 'Basil Thampi', 'Bipul Sharma', 'C Ganapathy',
       'C Green', 'C Madan', 'C Munro', 'C Nanda', 'C Sakariya',
       'C de Grandhomme', 'CA Ingram', 'CA Lynn', 'CA Pujara', 'CH Gayle',
       'CH Morris', 'CJ Anderson', 'CJ Dala', 'CJ Ferguson', 'CJ Green',
       'CJ Jordan', 'CJ McKay', 'CK Kapugedera', 'CK Langeveldt',
       'CL White', 'CM Gautam', 'CR Brathwaite', 'CR Woakes',
       'CRD Fernando', 'CV Varun', 'D Brevis', 'D Ferreira', 'D Jansen',
       'D Kalyankrishna', 'D Padikkal', 'D Pretorius', 'D Salunkhe',
       'D Wiese', 'D du Preez', 'DA Miller', 'DA Warner', 'DAJ Bracewell',
       'DB Das', 'DB Ravi Teja', 'DE Bollinger', 'DG Nalkande',
       'DH Yagnik', 'DJ Bravo', 'DJ Harris', 'DJ Hooda', 'DJ Hussey',
       'DJ Jacobs', 'DJ Malan', 'DJ Mitchell', 'DJ Muthuswami',
       'DJ Thornely', 'DJ Willey', 'DJG Sammy', 'DJM Short', 'DL Chahar',
       'DL Vettori', 'DM Bravo', 'DNT Zoysa', 'DP Conway', 'DP Nannes',
       'DP Vijaykumar', 'DPMD Jayawardene', 'DR Martyn', 'DR Sams',
       'DR Shorey', 'DR Smith', 'DS Kulkarni', 'DS Lehmann',
       'DT Christian', 'DT Patil', 'DW Steyn', 'Dhruv Jurel', 'E Lewis',
       'EJG Morgan', 'ER Dwivedi', 'F Behardien', 'F du Plessis',
       'FA Allen', 'FH Edwards', 'FY Fazal', 'Fazalhaq Farooqi',
       'G Coetzee', 'G Gambhir', 'GB Hogg', 'GC Smith', 'GC Viljoen',
       'GD McGrath', 'GD Phillips', 'GH Vihari', 'GHS Garton',
       'GJ Bailey', 'GJ Maxwell', 'GR Napier', 'GS Sandhu',
       'Gagandeep Singh', 'Gulbadin Naib', 'Gurkeerat Singh',
       'Gurnoor Brar', 'H Das', 'H Klaasen', 'H Sharma', 'HC Brook',
       'HE van der Dussen', 'HF Gurney', 'HH Gibbs', 'HH Pandya',
       'HM Amla', 'HR Shokeen', 'HV Patel', 'Harbhajan Singh',
       'Harmeet Singh', 'Harpreet Brar', 'Harpreet Singh', 'Harshit Rana',
       'I Malhotra', 'I Sharma', 'I Udana', 'IC Pandey', 'IC Porel',
       'IK Pathan', 'IR Jaggi', 'IS Sodhi', 'Imran Tahir',
       'Iqbal Abdulla', 'Ishan Kishan', 'J Arunkumar', 'J Botha',
       'J Fraser-McGurk', 'J Little', 'J Suchith', 'J Syed Mohammad',
       'J Theron', 'J Yadav', 'JA Morkel', 'JA Richardson', 'JC Archer',
       'JC Buttler', 'JD Ryder', 'JD Unadkat', 'JDP Oram', 'JDS Neesham',
       'JE Root', 'JE Taylor', 'JEC Franklin', 'JH Kallis', 'JJ Bumrah',
       'JJ Roy', 'JJ van der Wath', 'JL Denly', 'JL Pattinson',
       'JM Bairstow', 'JM Kemp', 'JM Sharma', 'JO Holder',
       'JP Behrendorff', 'JP Duminy', 'JP Faulkner',
       'JPR Scantlebury-Searles', 'JR Hazlewood', 'JR Hopes',
       'JR Philippe', 'JW Hastings', 'Jalaj S Saxena', 'Jaskaran Singh',
       'Joginder Sharma', 'K Goel', 'K Gowtham', 'K Kartikeya',
       'K Khejroliya', 'K Rabada', 'K Santokie', 'K Upadhyay', 'K Yadav',
       'KA Jamieson', 'KA Maharaj', 'KA Pollard', 'KAJ Roach',
       'KB Arun Karthik', 'KC Cariappa', 'KC Sangakkara', 'KD Karthik',
       'KH Devdhar', 'KH Pandya', 'KJ Abbott', 'KK Ahmed', 'KK Cooper',
       'KK Nair', 'KL Nagarkoti', 'KL Rahul', 'KM Asif', 'KM Jadhav',
       'KMA Paul', 'KMDN Kulasekara', 'KP Appanna', 'KP Pietersen',
       'KR Mayers', 'KR Sen', 'KS Bharat', 'KS Sharma', 'KS Williamson',
       'KT Maphaka', 'KV Sharma', 'KW Richardson', 'Kamran Akmal',
       'Kamran Khan', 'Karanveer Singh', 'Kartik Tyagi', 'Kuldeep Yadav',
       'Kumar Kushagra', 'L Ablish', 'L Balaji', 'L Ngidi', 'L Ronchi',
       'L Wood', 'LA Carseldine', 'LA Pomersbach', 'LB Williams',
       'LE Plunkett', 'LH Ferguson', 'LI Meriwala', 'LJ Wright',
       'LMP Simmons', 'LPC Silva', 'LR Shukla', 'LRPL Taylor',
       'LS Livingstone', 'Lalit Yadav', 'Liton Das', 'M Ashwin',
       'M Jansen', 'M Kaif', 'M Kartik', 'M Klinger', 'M Manhas',
       'M Markande', 'M Morkel', 'M Muralitharan', 'M Ntini',
       'M Pathirana', 'M Prasidh Krishna', 'M Rawat', 'M Shahrukh Khan',
       'M Siddharth', 'M Theekshana', 'M Vijay', 'M Vohra', 'M de Lange',
       'MA Agarwal', 'MA Khote', 'MA Starc', 'MA Wood', 'MB Parmar',
       'MC Henriques', 'MC Juneja', 'MD Mishra', 'MD Shanaka',
       'MDKJ Perera', 'MEK Hussey', 'MF Maharoof', 'MG Bracewell',
       'MG Johnson', 'MG Neser', 'MJ Clarke', 'MJ Guptill', 'MJ Henry',
       'MJ Lumb', 'MJ McClenaghan', 'MJ Santner', 'MJ Suthar',
       'MK Lomror', 'MK Pandey', 'MK Tiwary', 'ML Hayden', 'MM Ali',
       'MM Patel', 'MM Sharma', 'MN Samuels', 'MN van Wyk', 'MP Stoinis',
       'MP Yadav', 'MR Marsh', 'MS Bisla', 'MS Dhoni', 'MS Gony',
       'MS Wade', 'MV Boucher', 'MW Short', 'Mandeep Singh',
       'Mashrafe Mortaza', 'Mayank Dagar', 'Milind Kumar',
       'Misbah-ul-Haq', 'Mohammad Ashraful', 'Mohammad Asif',
       'Mohammad Hafeez', 'Mohammad Nabi', 'Mohammed Shami',
       'Mohammed Siraj', 'Mohit Rathee', 'Mohsin Khan', 'Monu Kumar',
       'Mujeeb Ur Rahman', 'Mukesh Choudhary', 'Mukesh Kumar',
       'Mustafizur Rahman', 'N Burger', 'N Jagadeesan', 'N Pooran',
       'N Rana', 'N Saini', 'N Thushara', 'N Wadhera', 'NA Saini',
       'NB Singh', 'ND Doshi', 'NJ Maddinson', 'NJ Rimmington',
       'NK Patel', 'NL McCullum', 'NLTC Perera', 'NM Coulter-Nile',
       'NS Naik', 'NT Ellis', 'NV Ojha', 'Naman Dhir', 'Navdeep Saini',
       'Naveen-ul-Haq', 'Nithish Kumar Reddy', 'Noor Ahmad', 'O Thomas',
       'OA Shah', 'OC McCoy', 'OF Smith', 'P Amarnath', 'P Awana',
       'P Chopra', 'P Dogra', 'P Dubey', 'P Kumar', 'P Negi',
       'P Parameswaran', 'P Prasanth', 'P Ray Barman', 'P Sahu',
       'P Simran Singh', 'P Suyal', 'PA Patel', 'PA Reddy',
       'PBB Rajapaksa', 'PC Valthaty', 'PD Collingwood', 'PD Salt',
       'PH Solanki', 'PJ Cummins', 'PJ Sangwan', 'PK Garg',
       'PM Sarvesh Kumar', 'PN Mankad', 'PP Chawla', 'PP Ojha', 'PP Shaw',
       'PR Shah', 'PSP Handscomb', 'PV Tambe', 'PVD Chameera',
       'PWH de Silva', 'Pankaj Singh', 'Parvez Rasool', 'Q de Kock',
       'R Ashwin', 'R Bhatia', 'R Bishnoi', 'R Dhawan', 'R Dravid',
       'R Goyal', 'R McLaren', 'R Ninan', 'R Parag', 'R Powell',
       'R Rampaul', 'R Ravindra', 'R Sai Kishore', 'R Sanjay Yadav',
       'R Sathish', 'R Sharma', 'R Shepherd', 'R Shukla', 'R Tewatia',
       'R Vinay Kumar', 'RA Bawa', 'RA Jadeja', 'RA Shaikh',
       'RA Tripathi', 'RD Chahar', 'RD Gaikwad', 'RE Levi',
       'RE van der Merwe', 'RG More', 'RG Sharma', 'RJ Gleeson',
       'RJ Harris', 'RJ Peterson', 'RJ Quiney', 'RJW Topley', 'RK Bhui',
       'RK Singh', 'RM Patidar', 'RN ten Doeschate', 'RP Meredith',
       'RP Singh', 'RR Bhatkal', 'RR Bose', 'RR Pant', 'RR Powar',
       'RR Raje', 'RR Rossouw', 'RR Sarwan', 'RS Bopara', 'RS Gavaskar',
       'RS Hangargekar', 'RS Sodhi', 'RT Ponting', 'RV Gomez', 'RV Patel',
       'RV Uthappa', 'RW Price', 'Rahmanullah Gurbaz', 'Ramandeep Singh',
       'Rashid Khan', 'Rasikh Salam', 'Ravi Bishnoi', 'S Anirudha',
       'S Aravind', 'S Badree', 'S Badrinath', 'S Chanderpaul',
       'S Dhawan', 'S Dube', 'S Gopal', 'S Joseph', 'S Kaul', 'S Kaushik',
       'S Ladda', 'S Lamichhane', 'S Midhun', 'S Nadeem', 'S Narwal',
       'S Rana', 'S Randiv', 'S Sandeep Warrier', 'S Sohal',
       'S Sreesanth', 'S Sriram', 'S Tyagi', 'S Vidyut', 'SA Abbott',
       'SA Asnodkar', 'SA Yadav', 'SB Bangar', 'SB Dubey', 'SB Jakati',
       'SB Joshi', 'SB Styris', 'SB Wagh', 'SC Ganguly', 'SC Kuggeleijn',
       'SD Chitnis', 'SD Hope', 'SD Lad', 'SE Bond', 'SE Marsh',
       'SE Rutherford', 'SH Johnson', 'SJ Srivastava', 'SK Raina',
       'SK Rasheed', 'SK Trivedi', 'SK Warne', 'SL Malinga', 'SM Boland',
       'SM Curran', 'SM Harwood', 'SM Katich', 'SM Pollock',
       'SMSM Senanayake', 'SN Khan', 'SN Thakur', 'SO Hetmyer',
       'SP Fleming', 'SP Goswami', 'SP Jackson', 'SP Narine', 'SPD Smith',
       'SR Tendulkar', 'SR Watson', 'SS Agarwal', 'SS Cottrell',
       'SS Iyer', 'SS Mundhe', 'SS Prabhudessai', 'SS Sarkar',
       'SS Shaikh', 'SS Tiwary', 'SSB Magala', 'ST Jayasuriya',
       'STR Binny', 'SV Samson', 'SW Billings', 'SW Tait', 'SZ Mulani',
       'Sachin Baby', 'Salman Butt', 'Sameer Rizvi', 'Sandeep Sharma',
       'Sanvir Singh', 'Saurav Chauhan', 'Shahbaz Ahmed', 'Shahid Afridi',
       'Shakib Al Hasan', 'Shashank Singh', 'Shivam Mavi',
       'Shivam Sharma', 'Shivam Singh', 'Shoaib Ahmed', 'Shoaib Akhtar',
       'Shoaib Malik', 'Shubman Gill', 'Sikandar Raza', 'Simarjeet Singh',
       'Sohail Tanvir', 'Sonu Yadav', 'Subhransu Senapati', 'Sumit Kumar',
       'Sunny Gupta', 'Sunny Singh', 'Suyash Sharma', 'Swapnil Singh',
       'T Banton', 'T Henderson', 'T Kohler-Cadmore', 'T Kohli',
       'T Mishra', 'T Natarajan', 'T Shamsi', 'T Stubbs', 'T Taibu',
       'T Thushara', 'TA Boult', 'TD Paine', 'TG Southee', 'TH David',
       'TK Curran', 'TL Seifert', 'TL Suman', 'TM Dilshan', 'TM Head',
       'TM Srivastava', 'TP Sudhindra', 'TR Birt', 'TS Mills',
       'TU Deshpande', 'Tanay Thyagarajan', 'Tanush Kotian',
       'Tejas Baroka', 'Tilak Varma', 'U Kaul', 'UA Birla', 'UBT Chand',
       'UT Khawaja', 'UT Yadav', 'Umar Gul', 'Umran Malik', 'V Kaverappa',
       'V Kohli', 'V Pratap Singh', 'V Sehwag', 'V Shankar',
       'V Viyaskanth', 'VG Arora', 'VH Zol', 'VR Aaron', 'VR Iyer',
       'VRV Singh', 'VS Malik', 'VS Yeligati', 'VVS Laxman', 'VY Mahesh',
       'Vijaykumar Vyshak', 'Virat Singh', 'Vishnu Vinod',
       'Vivrant Sharma', 'W Jaffer', 'WA Mota', 'WD Parnell', 'WG Jacks',
       'WP Saha', 'WPUJC Vaas', 'Washington Sundar',
       'X Thalaivan Sargunam', 'Y Gnaneswara Rao', 'Y Nagar',
       'Y Prithvi Raj', 'Y Venugopal Rao', 'YA Abdulla', 'YBK Jaiswal',
       'YK Pathan', 'YS Chahal', 'YV Dhull', 'YV Takawale', 'Yash Dayal',
       'Yash Thakur', 'Yashpal Singh', 'Younis Khan', 'Yudhvir Singh',
       'Yuvraj Singh', 'Z Khan']